### ISSUE TITLE
Flag commits without tests

### ISSUE THREAD

**Issue by gguuss** [googleapis/github-repo-automation#324]
On the python-docs-samples repo, we have had a large influx of commits without tests and I'm having a bad time enforcing it.  We should produce automation that disallows such commits.

**Comment by gguuss** [comment]
Could investigate using `nox --missingtests`

**Comment by bcoe** [comment]
@gguuss I think it would be better to open an issue here :+1: 

https://github.com/googleapis/repo-automation-bots

**Comment by gguuss** [comment]
Closing at the suggestion of @bcoe, [moved to here](https://github.com/googleapis/repo-automation-bots/issues/108).
