### ISSUE TITLE
repo untag feature

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/github-repo-automation#447]
sometimes after tagging a PR, due to some reasons we need to untag. For instance, `automerge` is facing backend quota issue -- we need to untag the ones that did not go through successfully.

It would be helpful to have the feature to `untag`

**Comment by JustinBeckwith** [comment]
👋  @stephaniewang526 this is a great idea.  Any interest in making the change?  Shouldn't be too bad - mostly just copying `src/tag-prs.ts`, and using that (short!) file as a guide on how to implement the command.  I'd be happy to work together if you're interested!

**Comment by stephaniewang526** [comment]
sure -- i can take a look

**Comment by bcoe** [comment]
@sofisl added this functionality recently:

```
 $ repo untag [--branch branch] [--author author] [--title title] label1
```

see: https://github.com/googleapis/github-repo-automation/pull/454
