### ISSUE TITLE
adding support for individual files over 1MB over Github Database API

### ISSUE THREAD

**Issue by vmizg** [googleapis/github-repo-automation#555]
**Is your feature request related to a problem? Please describe.**

I noticed in the README of the repository that there is a clear note about no support for Github Database API (in the context of multiple files in one commit).

Unfortunately, in my case, that seems to cause an issue for one very specific use case: `package-lock.json` 😃  As part of a polyrepo update, I sometimes need to bump the package version, and this file often exceeds that 1MB limit, which requires me to clone the repo separately and use npm cli or manual update in the same branch.

 **Describe the solution you'd like**

Support file size checking and use Github Database API selectively when a file that is being committed exceeds the 1MB limit.

 **Describe alternatives you've considered**

None. Manual updates via Github CLI only.

 **Additional context**

I have the implementation ready on my side for both "getFile" and "updateFileInBranch" with the use of Github DB API. It does not resolve the single-commit-per-file issue though as it would require some refactoring of the ["updateRepo" implementation](https://github.com/googleapis/github-repo-automation/blob/4fc5cb3111d831d296ac0395835a1d1f5cb578d7/src/lib/update-repo.ts#L104).

**Comment by SurferJeffAtGoogle** [comment]
I'm sorry @vmizg but we don't have time to implement this feature request.  You are welcome to open a pull request to implement it and re-open this issue.
